services:
    mqtt:
        image: eclipse-mosquitto
        container_name: iobroker-zigbee2mqtt-mqtt
        restart: unless-stopped
        expose:
            - 1883
            - 9001
        volumes:
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        healthcheck:
            test: ['CMD', 'mosquitto_sub', '-t', '$$SYS/#', '-C', '1', '-i', 'healthcheck', '-W', '3']
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 20s
    zigbee2mqtt:
        container_name: iobroker-zigbee2mqtt-zigbee2mqtt
        restart: unless-stopped
        image: koenkk/zigbee2mqtt
        depends_on:
            - mqtt
        expose:
            - 8080
        # Map the adapter here if it is attached by usb
        #devices:
        #- /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-06M_269fd606138bef118ab227ccef8776e9-if00-port0:/dev/ttyUSB0
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
        environment:
            - TZ=Europe/Berlin

    iobroker:
        build: ./iobroker
        container_name: iobroker-zigbee2mqtt
        hostname: iobroker-zigbee2mqtt
        # This port is only internal, so we can work on this while another instance of ioBroker is running on the host
        expose:
            - 8081
        volumes:
            - ..:/workspace:cached
        environment:
            # using non-default ports to not interfere with integration tests
            - IOB_OBJECTSDB_TYPE=jsonl
            - IOB_OBJECTSDB_HOST=127.0.0.1
            - IOB_OBJECTSDB_PORT=29001
            - IOB_STATESDB_TYPE=jsonl
            - IOB_STATESDB_HOST=127.0.0.1
            - IOB_STATESDB_PORT=29000
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
            - TZ=Europe/Berlin
            - SETGID=1000

    # Reverse proxy to load up-to-date admin sources from the repo
    nginx:
        image: nginx:latest
        depends_on:
            - iobroker
        links:
            - iobroker
        container_name: nginx-zigbee2mqtt
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ..:/workspace:cached
        ports:
            # Port will be forwarded in the devcontainer
            - 80
